import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { isAiExcludedMarkdown } from "./access.js";
import { walkMarkdown } from "./walk.js";

const STATIC_ENTRIES = ["_protected/", ".obsidian/"];

export async function listExcludedMarkdown(root: string): Promise<string[]> {
  const excluded: string[] = [];
  await walkMarkdown(root, async (relative, full) => {
    const content = await readFile(full, "utf8");
    if (isAiExcludedMarkdown(content)) excluded.push(relative);
  });
  return excluded.sort((a, b) => a.localeCompare(b));
}

export async function regenerateCursorIgnore(root: string): Promise<void> {
  const excluded = await listExcludedMarkdown(root);
  const lines = [
    "# generated by nousarium",
    ...STATIC_ENTRIES,
    "",
    "# ai_access: excluded",
    ...excluded,
  ];
  await writeFile(path.join(root, ".cursorignore"), `${lines.join("\n")}\n`, "utf8");
}
